=== candango/myfuses/trunk/myfuses.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT fusebox (circuits+, classes?, parameters?, globalfuseactions?, plugins?)>
<!ELEMENT myfuses (circuits+, classes?, parameters?, globalfuseactions?, plugins?)>

<!ELEMENT circuits (circuit*)>
<!ELEMENT circuit EMPTY>
<!ATTLIST circuit
	alias CDATA #REQUIRED
	path CDATA #REQUIRED
	parent CDATA #IMPLIED
	relative (true | false | yes | no) "true"
>

<!ELEMENT classes (class*)>
<!ELEMENT class EMPTY>
<!ATTLIST class
	alias CDATA #REQUIRED
	type (component | java) "component"
	classpath CDATA #REQUIRED
	constructor CDATA #IMPLIED
>

<!ELEMENT globalfuseactions (appinit?, preprocess?, postprocess?)>
<!ELEMENT appinit ((do | fuseaction)*)>
<!ELEMENT preprocess ((do | fuseaction)*)>
<!ELEMENT postprocess ((do | fuseaction)*)>

<!ELEMENT do EMPTY>
<!ATTLIST do
	action CDATA #REQUIRED
>

<!ELEMENT fuseaction EMPTY>
<!ATTLIST fuseaction
	action CDATA #REQUIRED
>

<!ELEMENT plugins (phase*)>
<!ELEMENT phase (plugin*)>
<!ATTLIST phase
	name (fuseactionException | postFuseaction | postProcess | preFuseaction | preProcess | processError) #REQUIRED
>

<!ELEMENT plugin (parameter*)>
<!ATTLIST plugin
	name CDATA #REQUIRED
	file CDATA #IMPLIED
	template CDATA #IMPLIED
	path CDATA #IMPLIED
>

<!ELEMENT parameters (parameter*)>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== candango/myfuses/myfuses_tools/myfuses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myfuses PUBLIC "-//MYFUSES//DTD MYFUSES 1.0 Strict//EN"
    "http://www.candango.org/publish/formats/myfuses.dtd">
<!--
    All circuits, classes, lexicons, parameters, globalfuseactions and plugins 
    used in MyFuses Application are configured in here.
    We are using MyFuses in a non-strict style.
    More information about MyFuses:
        https://candango.org/project/myfuses
        https://github.com/candango/myfuses
    @author: Flavio Garcia <piraz at candango.org>
-->
<myfuses>
    <circuits>
        <circuit alias="tools" path="tools/" parent="" />
        <circuit alias="application" path="application/" parent="tools" />
    </circuits>

    <classes>
    </classes>

    <parameters>
        <parameter name="fuseactionVariable" value="fuseaction" />
        <parameter name="defaultFuseaction" value="tools.start" />
        <parameter name="precedenceFormOrUrl" value="form"/>
        <parameter name="mode" value="production"/>
        <parameter name="password" value=""/>
        <parameter name="parseWithComments" value="true" />
        <parameter name="conditionalParse" value="true" />
        <parameter name="allowLexicon" value="true" />
        <parameter name="ignoreBadGrammar" value="true"/>
        <parameter name="useAssertions" value="true" />
        <parameter name="scriptLanguage" value="php5" />
        <parameter name="scriptFileDelimiter" value="php"/>
        <parameter name="maskedFileDelimiters" value="htm,cfm,cfml,php,php4,asp,aspx,class,inc"/>
        <parameter name="characterEncoding" value="iso-8859-1"/>
    </parameters>

    <globalfuseactions>
        <preprocess>
        </preprocess>
        <postprocess>
        </postprocess>
    </globalfuseactions>

    <plugins>
        <phase name="preProcess">
            <plugin name="MyFusesApplicationSecurity"></plugin>
        </phase>
        <phase name="preFuseaction">
        </phase>
        <phase name="postFuseaction">
        </phase>
        <phase name="fuseactionException">
        </phase>
        <phase name="postProcess">
        </phase>
        <phase name="processError">
        </phase>
    </plugins>

</myfuses>
